# Generated by Django 3.1.4 on 2021-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
